[package]
name = "falcon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pqcrypto-falcon = "0.2.0"
pqcrypto-traits = "0.3.4"
hex = "0.4.3"


[lib]
crate-type=["cdylib"]
